### ISSUE TITLE
Feature Request: Allow the inverse

### ISSUE THREAD

**Issue by IanMoroney** [chilicat/terraform-provider-pkcs12#1]
I also had a requirement to create PKCS12 from PEM files, so thank you for making this provider!!

I was wondering, would it be possible for you to also do the inverse?
Allow PEM files to be created from a PFX file.
I would imagine:
A data block for the PFX file
A resource block for the certificate (in PEM format)
A resource block for the private key (in PEM format, with no password, or password to be optional as some requirements need PEM format with no password on the file, and some allow a private key password)
Maybe a resource block for the ca cert?

**Comment by chilicat** [comment]
Unfortunately it does not itch my needs at the moment. I'm open for merge requests.
