### ISSUE TITLE
TLS certificates encrypted with password are empty

### ISSUE THREAD

**Issue by Bhavik123-practice** [chilicat/terraform-provider-pkcs12#11]
I am following the exact approach described in this github repo: https://github.com/gehlotanish/terraform-x509/tree/main

Certificate is created in pfx format and when trying to export private key, the password is empty instead of the one I provided. Can someone please assist?

**Comment by schnabel45** [comment]
I found the exact same issue occurs randomly for no apparent reason. Depending on when you run the provider the password will either be blank, or the expected value.

**Comment by chilicat** [comment]
The new version (v0.1.0) provides a new param (`private_key_pass` ) to define a password for a encrypted private key. 
Note: The private key is always stored unencrypted in the the PKCS store. For my understanding PKCS is encrypting the content on its own.
