### ISSUE TITLE
Provider can no longer accept Fullchain-type certificates

### ISSUE THREAD

**Issue by alexpilon666** [chilicat/terraform-provider-pkcs12#12]
Ever since [this commit here](https://github.com/chilicat/terraform-provider-pkcs12/commit/131f206f43d50bd3b65be182b03b4f79ed34f295) which was part of a refactor for v0.1.0 around a month ago, we can no longer provide a full certificate chain (public cert + CA/intermediate certs) to `cert_pem`. It instead returns an error saying `cert_pem must contains exactly one certificate`. 

This is problematic for us because we use the `pcks12_from_pem` resource to create PFX files from two different sources, one of which, `azurerm_key_vault_certificate_data`, only provides a fullchain and privatekey and does not provide a separate attribute to get the certificate and chain separately.

Is there a way the provider could be adjusted to support this kind of scenario ? For now I configured Terraform to only use version 0.0.7, which does not contain this fix, but we're not big fans of using old/unsupported versions of providers.

Thanks!

**Comment by chilicat** [comment]
@alexpilon666 can you give 0.2.1-pre a try?

https://registry.terraform.io/providers/chilicat/pkcs12/0.2.1-pre
