### ISSUE TITLE
An additional argument for encoder type

### ISSUE THREAD

**Issue by ihor-lysukha** [chilicat/terraform-provider-pkcs12#13]
Hello there,

Thank you for this useful Terraform provider, good job.

Unfortunately, I was not able to use it for Google Cloud. It was necessary to create a resource with PKCS12 keystore. Still, it turned out that it was created using OpenSSL v1.x and other resources in the Google Cloud project refused to accept the unsupported keystore format. In this regard, could you add another argument to set up the encoder type, e.g. Modern2023 or Legacy?

Best regards.

**Comment by chilicat** [comment]
@ihor-lysukha  Can you try **0.2.0-pre**. I have upgraded the library which creates the pkcs12 keystore

**Comment by ihor-lysukha** [comment]
> @ihor-lysukha Can you try **0.2.0-pre**. I have upgraded the library which creates the pkcs12 keystore

Awesome, thanks a lot! I'll try this ASAP.

**Comment by ihor-lysukha** [comment]
Hi,

I've tried to use an updated version but, unfortunately, I got the following error from the NodeJS-based Cloud Run service:
`Error opening a TLS connection: error:11800071:PKCS12 routines:PKCS12_parse:mac verify failure:../crypto/pkcs12/p12_kiss.c:71`

If anything, I checked that the password is correct and matches the keystore.
Is it possible that OpenSSL 1.x is still being used when creating the keystore?

**Comment by chilicat** [comment]
Not sure, the lib doc said that "modern" methd is used. If you can give 0.2.2-pre a try, it uses the "moder" encode explicitly:

https://github.com/chilicat/terraform-provider-pkcs12/blob/645756ab75c635774e46dde737d859303e88e7a6/pkcs12/resource_pkcs12.go#L113

Sorry for asking you to test that, we did not run into this issue yet.

**Comment by ihor-lysukha** [comment]
It's OK. 
Yes, I've tried exactly the latest version, 0.2.2-pre.
We will also double-check everything on our side.

**Comment by ihor-lysukha** [comment]
@chilicat
To generate a password for the keystore, we use the Terraform resource `random_password`. With its help, a password was created that included special symbols. As it turned out, our application incorrectly substituted the value of such a password into the URI string for connecting to the DB instance. That is, the problem was not with the keystore itself. It all works now like a charm.
Thank you for useful Terraform provider!

**Comment by chilicat** [comment]
Thanks for reporting back. I'm going to release the provider now.
