### ISSUE TITLE
SHA1 Thumbprint Output

### ISSUE THREAD

**Issue by the-cashman** [chilicat/terraform-provider-pkcs12#2]
Would it be possible to add an output for the sha1 thumbprint besides the resulting base64?

**Comment by ghost** [comment]
Yes I need to pass the thumbprint to an automation account, would be nice to have that.

**Comment by chilicat** [comment]
@devlincashman @ghost

you mean the SHA1 Thumbprint for the given certificate?
I believe you can gather this information with the default Terraform TLS module:
https://registry.terraform.io/providers/hashicorp/tls/latest/docs/data-sources/certificate




`
data "tls_certificate" "example_content" {
  content = file("example.pem")
}
`
The resource provides a [sha1_fingerprint output variable](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/data-sources/certificate#sha1_fingerprint)
