### ISSUE TITLE
CA certificates are not being included in pkcs12 file

### ISSUE THREAD

**Issue by angelbulas** [chilicat/terraform-provider-pkcs12#4]
In theory, this provider should include the CA certificates when you use the parameter ca_pem, but if you inspect the pkcs12 file generated, it does not include them, I'm using:

openssl pkcs12 -in certificate.pfx -cacerts -nokeys -chain | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > cacerts.cer

But the file cacerts.cer is empty, looks like you can't include them and in consecuence, when you try to use the generated pfx, it send errors about missing intermediate certs.

**Comment by hargut** [comment]
This is an interesting situation, I just came across it. It seems to be, that it works in some conditions as expected, but not always.

In my scenario I just created a pkcs12, and wanted to add an additional intermediate ca to `ca_pem` using a simple `join("", [ca1.pem, ca2.pem])`.

As it didn't work as expected i started to fiddle around, and at some point I got the result I needed.

During the change when it was included in the result, terraform logged
```
pkcs12_from_pem.keystore: Destroying... [id=17a6d150dfdee0a26d9721028f4b95b69d626080]
pkcs12_from_pem.keystore: Destruction complete after 0s
pkcs12_from_pem.keystore: Creating...
pkcs12_from_pem.keystore: Creation complete after 0s [id=5c3cd875b5a2125c34b331b1036a4cb1892b34b4]
```

**Comment by chilicat** [comment]
@hargut could it be that ca1 and ca2 has no newline which would mess up the TAG/Block finding?

Could you try:
`
join("\n", [ca1.pem, ca2.pem])
`

**Comment by chilicat** [comment]
Please try the new version v0.1.0 it has some stricter decoding/parsing.

**Comment by hargut** [comment]
Thank you for the feedback and update.
We'll switch to the new version.
