### ISSUE TITLE
loadCertficates and check for cert.PrivateKey don't go well together

### ISSUE THREAD

**Issue by maschoene** [chilicat/terraform-provider-pkcs12#8]
When you pass a bad string as `key_pem`, `loadCertificates` will not report an error and will leave `cert.PrivateKey` `nil` ([utils.go#L20](https://github.com/chilicat/terraform-provider-pkcs12/blob/master/pkcs12/utils.go#L20))

In [resource_pkcs12.go#L79](https://github.com/chilicat/terraform-provider-pkcs12/blob/master/pkcs12/resource_pkcs12.go#L79) `cert.PrivateKey` is checked to not be `""`, but it will still be `nil` and provider will continue.

**Comment by chilicat** [comment]
Latest version (v0.0.1) returns an error if no private key can be parsed
